apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  clusterIP: None
  selector:
    app: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order
