apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: outbox-pattern
build:
  artifacts:
    - image: order
      context: order
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: payment
      context: payment
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - order\deployment.yaml
    - payment\deployment.yaml
